steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/n8nkineo/n8n-cloudrun:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/n8nkineo/n8n-cloudrun:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'n8nkineo'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/n8nkineo/n8n-cloudrun:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/n8nkineo/n8n-cloudrun:latest'
